### ISSUE TITLE
Does not build with SBCL 2.0.9 - :initform/:type issue

### ISSUE THREAD

**Issue by quicklisp** [tychoish/cl-grip#1]
I get this:  `Constant NIL conflicts with its asserted type GRIP.LEVEL:PRIORITY.`

Full log here: http://report.quicklisp.org/2020-09-29/failure-report/cl-grip.html#cl-grip

**Comment by tychoish** [comment]
oh no! I'll look into this very soon!

**Comment by tychoish** [comment]
I've pushed a fix that should address this issue!

**Comment by quicklisp** [comment]
I'm afraid not - there's still a slot with `:initform nil` that has a `:type string`, which causes the build to fail.

**Comment by tychoish** [comment]
I did another pass and think I got it.

**Comment by quicklisp** [comment]
Nope.

```
; caught WARNING:
;   Constant NIL conflicts with its asserted type GRIP.LEVEL:PRIORITY.
;   See also:
;     The SBCL Manual, Node "Handling of Types"
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {100\
1A58103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-grip" "src" "message">
```

**Comment by quicklisp** [comment]
Looks good now, thanks!
