### ISSUE TITLE
ASDF loading of tests fails on SBCL due to bad type declarations

### ISSUE THREAD

**Issue by brown** [tychoish/cl-grip#4]
The latest SBCL cannot load and run cl-grip tests.  The Quicklisp failure log is here:  http://report.quicklisp.org/2023-11-04/failure-report/cl-grip.html#cl-grip_ext

This pull request fixes the issue:  https://github.com/tychoish/cl-grip/pull/3

**Comment by tychoish** [comment]
Hope this is resolved!

**Comment by tychoish** [comment]
(thanks for the assist! let me know if there's more I need to do!)

**Comment by brown** [comment]
Thanks for reviewing and merging the change!
